### ISSUE TITLE
[dry-configurable] warnings

### ISSUE THREAD

**Issue by jidylle** [uploadcare/uploadcare-rails#103]
### Question

Hi,
We added the uploadcare-ruby-3.2.0 gem and now we have several warnings each time we started our app.

"_vendor/bundle/gems/uploadcare-ruby-3.2.0/lib/uploadcare.rb:29:in `<top (required)>' [dry-configurable] default value as positional argument to settings is deprecated and will be removed in the next major version
Provide a `default:` keyword argument instead_"
 

May be a way to fix it : https://hanamimastery.com/episodes/5-configure-anything-with-dry-configurable 
(search keyword "constructor" in the page)

How to fix it ?
Thanks

**Comment by dmitrijivanchenko** [comment]
Hi, @jidylle!

Thanks for the suggestion!

The warning does not affect functionality, so you can simply disable it by setting parameters in your project:

```ruby
Dry::Configurable.warn_on_setting_constructor_block false
Dry::Configurable.warn_on_setting_positional_default false
```

source https://github.com/dry-rb/dry-configurable/blob/master/CHANGELOG.md

Probably we will fix it in next major versions.
Thanks!

**Comment by jidylle** [comment]
Thanks Dmitry for your answer.
I tested it, but it did not work. Where do we have to put this 2 lines
configuration ? In which file ?
Thanks.

Le mar. 7 déc. 2021 à 04:54, dmitrijivanchenko ***@***.***> a
écrit :

**Comment by dmitrijivanchenko** [comment]
Hey, @jidylle!

I guess the good place for these lines is a initializer. Have you tried to add them in an existing or new initializer file (in Rails apps it usually located in `config/initializers/<your_filename>.rb` - smth like `config/initializers/dry_configurable.rb`)?

Have a nice day!

**Comment by jidylle** [comment]
Thanks Dmitri.

This is what I tried (in the initializers folder) but unfortunately the
result is the same, the warnings are still displayed :/ (see attached).

[image: Capture_d_écran_15_12_2021_17_37.png]

**Comment by jidylle** [comment]
Hi Dmitry,
Another solution to remove this "depecrated" warning?
Thank u.

Le mer. 15 déc. 2021 à 17:41, Jérôme IDYLLE ***@***.***> a
écrit :

**Comment by dmitrijivanchenko** [comment]
Hi, @jidylle !

Sorry for late reply! Yes, you are right that initializer won't work because they are loaded after gems (uploadcare gem).
Another hack you can do is placing these two strings in the `config/application.rb` file.

But you should place them along with `require 'dry-configurable'` before all gems load string.
See the pic

![dry-conf-hack](https://user-images.githubusercontent.com/29576452/147628675-12c26f38-61ec-4c36-b7d6-afbe78115325.png)

I also believe that you can move these lines (8-11) to a separate file and require this new file in the `config/application.rb` for more readability and decreasing size of the `config/application.rb` file.

Have a nice day!

**Comment by jidylle** [comment]
It works. Thank you Dmitri.
